In [1]:
import numpy as np

In [2]:
a  =[1,2,3,4,5,6,7,8,9]                           #Python array


In [3]:
print(a)


[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
A = np.array(a)                               #numpy array

In [5]:
print(A)


[1 2 3 4 5 6 7 8 9]


In [6]:
A.shape         #Returns the dimension

(9,)

In [7]:
A.reshape(1,9)               #Returns a multi-dimensional matrix

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
A.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(2,20,3)                #a.arange(start,stop,step)

array([ 2,  5,  8, 11, 14, 17])

In [10]:
np.zeros((4,3))                #Returns nxm matrix containing zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,3))                  #Returns nxm matrix containing one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.full((3,3),'$')                   #np.full(shape,fill_value,dtype)

array([['$', '$', '$'],
       ['$', '$', '$'],
       ['$', '$', '$']], dtype='<U1')

In [13]:
np.eye(4)                        #eye stands  for identity returns identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
a = np.eye(3)            #Multiply Two matrices

In [15]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
b = np.arange(1,10).reshape((3,3))

In [17]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(1,18,2).reshape((3,3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [19]:
m = np.dot(a,b)               #Performs Actual dot Product

In [20]:
m

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [21]:
sum = np.sum(m)                           #Adding all elements of a matrix

In [22]:
sum

45.0

In [23]:
np.sum(m,axis = 1)                             #sum along rows ---->  axis =  1

array([ 6., 15., 24.])

In [24]:
np.sum(m,axis = 0)                                 #sum along columns -------> axis = 0

array([12., 15., 18.])